// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// naive_cpp
NumericVector naive_cpp(NumericVector v);
RcppExport SEXP _Rprojects_naive_cpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(naive_cpp(v));
    return rcpp_result_gen;
END_RCPP
}
// kadane_cpp
NumericVector kadane_cpp(NumericVector v);
RcppExport SEXP _Rprojects_kadane_cpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(kadane_cpp(v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rprojects_naive_cpp", (DL_FUNC) &_Rprojects_naive_cpp, 1},
    {"_Rprojects_kadane_cpp", (DL_FUNC) &_Rprojects_kadane_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rprojects(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
