# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_Rprojects_rcpp_hello_world`)
}

timesTwo <- function(x) {
    .Call(`_Rprojects_timesTwo`, x)
}

insertion_sort_cpp <- function(v) {
    .Call(`_Rprojects_insertion_sort_cpp`, v)
}

