# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

naive_cpp <- function(v) {
    .Call(`_Rprojects_naive_cpp`, v)
}

kadane_cpp <- function(v) {
    .Call(`_Rprojects_kadane_cpp`, v)
}

